# HTML Attributes
EMAIL_SIZE = 120
PASSWORD_SIZE = 128

# Routes
BROWSE_PRODUCTS_PAGE = '/products'

LOGIN_PAGE = '/login'
LOGIN_PAGE_PARAM = LOGIN_PAGE + '/<step>'
LOGIN_PAGE_EXISTING_USER = LOGIN_PAGE + '/existing_user'
LOGIN_PAGE_FORGOT_PASSWORD = LOGIN_PAGE + '/forgot_password'
LOGIN_PAGE_NEW_USER = LOGIN_PAGE + '/new_user'
